<?php 
use ZfcDatagrid\Column;
use ZfcDatagrid\Column\Type;
use ZfcDatagrid\Column\Style;
?>

<form name="form_<?php echo $this->gridId; ?>" method="post" action="<?php echo $this->url(null, array(), array(), true); ?>">

    <input type="submit" style="width: 0px; height:0px; margin: 0; padding: 0; border: 0;" name="hiddenSubmit" />
    <input type="hidden" name="<?php echo $this->parameterNames['sortColumns']; ?>" value="<?php echo $this->activeParameters[$this->parameterNames['sortColumns']]; ?>" />
    <input type="hidden" name="<?php echo $this->parameterNames['sortDirections']; ?>" value="<?php echo $this->activeParameters[$this->parameterNames['sortDirections']]; ?>" />

    
<?php echo $this->toolbar; ?>

<?php 

$orderOnclick = 'document.forms[\'form_'.$this->gridId.'\'].elements[\'' . $this->parameterNames['sortColumns'] . '\'].value = \'%s\';';
$orderOnclick .= 'document.forms[\'form_'.$this->gridId.'\'].elements[\'' . $this->parameterNames['sortDirections'] . '\'].value = \'%s\';';
$orderOnclick.= 'document.forms[\'form_'.$this->gridId.'\'].submit(); return false;';

$classes = $this->tableClasses;
if($this->rowClickAction !== null){
    $classes[] = 'table-hover';
}
?>

<?php echo $this->partial($this->templateToolbar);?>

<table class="<?php echo implode(' ', $classes); ?>">
    <thead>
        <tr>
            <?php 
            foreach($this->columns as $column){
                /* @var $column \ZfcDatagrid\Column\AbstractColumn */
                $classes = array();
                $styles = array();
                
                $id = $column->getUniqueId();
                
                $label = '';
                if($column->getLabel() != ''){
                    $label = $this->translate($column->getLabel());
                }
                
                $width = $column->getWidth();
                if($width != ''){
                    $styles[] = 'width: '.$this->escapehtmlattr($width).'%';
                }
                
                
                if($column->isHidden() === true){
                    $classes[] = 'hidden';
                }
                if($column->getType() instanceof Type\Number){
                    $styles[] = 'text-align: right';
                }
                ?>
                <th id="<?php echo $this->escapehtmlattr($id); ?>" class="<?php echo implode(',', $classes); ?>" style="<?php echo implode(';', $styles); ?>">
                    
                    <?php if($column->isUserSortEnabled() === true): 
                        if($column->isSortActive() === true && $column->getSortActiveDirection() === 'ASC'){
                            $direction = 'DESC';
                        } else{
                            $direction = 'ASC';
                        }
                        ?>
                        <a href="<?php echo 
                            $this->url(null, 
                                array(),
                                array(
                                    'query' => array_merge($this->activeParameters, array(
                                            $this->parameterNames['sortColumns'] => $column->getUniqueId(),
                                            $this->parameterNames['sortDirections'] => $direction,
                                        )
                                    )
                                ),
                                true
                            );?>
                        " onclick="<?php echo sprintf($orderOnclick, $column->getUniqueId(), $direction); ?>">
                            <?php echo $this->escapeHtml($label); ?>
                        </a>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($label); ?>
                    <?php endif; ?>
                    
                    <?php 
                    if($column->isSortActive() === true){
                        if($column->getSortActiveDirection() === 'ASC'):?>
                            <i class="icon-chevron-down glyphicon glyphicon-chevron-down"></i>
                        <?php else: ?>
                            <i class="icon-chevron-up glyphicon glyphicon-chevron-up"></i>
                        <?php endif;
                    }
                    ?>
                </th>
                <?php
            }
            ?>
        </tr>
        
        <!-- User filters -->
        <?php if($this->isUserFilterEnabled === true):?>
            <tr>
                <?php
                foreach($this->columns as $column){
                    /* @var $column \ZfcDatagrid\Column\AbstractColumn */

                    $classes = array();
                    if($column->isHidden() === true){
                        $classes[] = 'hidden';
                    }
                    
                    $htmlFilter = '';
                    if ($column->isUserFilterEnabled() === true) {

                        if ($column->hasFilterSelectOptions() === true) {
                            $htmlFilter = '<select name="toolbarFilters[' . $column->getUniqueId() . ']" style="width: 80%" onchange="this.form.submit()">';
                            foreach ($column->getFilterSelectOptions() as $value => $option) {
                                if ($column->getFilterActiveValue() != '' && $column->getFilterActiveValue() == $value) {
                                    $htmlFilter .= '<option value="' . $value . '" selected="selected">' . $option . '</option>';
                                } else {
                                    $htmlFilter .= '<option value="' . $value . '">' . $option . '</option>';
                                }
                            }
                            $htmlFilter .= '</select>';
                        } else {
                            $htmlFilter = '<input type="text" name="toolbarFilters[' . $column->getUniqueId() . ']" style="width: 80%" value="' . $column->getFilterActiveValue() . '" />';
                        }
                    }
                    ?>
                    <td class="<?php echo implode(',', $classes); ?>">
                        <?php echo $htmlFilter; ?>
                    </td>
                    <?php
                }
                ?>
            </tr>
        <?php endif; ?>
    </thead><!-- END table header -->
    
    <!-- Start table BODY -->
    <tbody>
        <?php foreach($this->data as $row): ?>
            <?php echo $this->bootstrapTableRow($row, $this->columns, $this->rowClickAction, $this->rowStyles); ?>
        <?php endforeach; ?>
    </tbody>
</table>

<?php
$pages = $this->paginator->getPages();

$paginatorOnclick = 'document.forms[\'form_'.$this->gridId.'\'].elements[\'' . $this->parameterNames['currentPage'] . '\'].value = %s;';
$paginatorOnclick.= 'document.forms[\'form_'.$this->gridId.'\'].submit(); return false;';
?>
<!-- Start Pagination -->
<div class="row-fluid row">
    <div class="span4 col-md-4">
        <?php echo $this->translate('Page').' '.$this->paginator->getCurrentPageNumber().' '.$this->translate('of').' '.$this->paginator->count(); ?>
    </div>
    <div class="span4 col-md-4">
        <div class="pagination">
        
            <input type="hidden" name="<?php echo $this->parameterNames['currentPage']; ?>" value="<?php echo $pages->current; ?>" />
            <?php if (count($pages->pagesInRange) > 1): ?>
            <ul class="pagination">
                <?php if($pages->current > 1):?>
                    <li><a href="<?php echo 
                            $this->url(null, 
                                array(),
                                array(
                                    'query' => array_merge($this->activeParameters, array(
                                            $this->parameterNames['currentPage'] => $pages->current - 1
                                        )
                                    )
                                ),
                                true
                            );?>
                        "  onclick="<?php echo sprintf($paginatorOnclick, $pages->current - 1);?>">
                            &laquo;
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">&laquo;</a>
                    </li>
                <?php endif;?>
                
                <?php foreach($pages->pagesInRange as $page):?>
                    <?php 
                    $add = '';
                    if($pages->current === $page){
                        $add = 'class="active"';
                    }
                    
                    if($pages->current != $page){
                        $url = $this->url($this->matchedRouteName, 
                            array(),
                            array(
                                'query' => array_merge($this->activeParameters, array(
                                        $this->parameterNames['currentPage'] => $page
                                    )
                                )
                            ),
                            true
                        );
                    } else{
                        $url = '#';
                    }
                    ?>
                    <li <?php echo $add; ?>>
                        <a href="<?php echo $url; ?>" onclick="<?php echo sprintf($paginatorOnclick, $page);?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php endforeach; ?>
                
                <?php if($pages->current < $pages->pageCount): ?>
                    <li>
                        <a href="<?php echo 
                            $this->url($this->matchedRouteName, 
                                array(),
                                array(
                                    'query' => array_merge($this->activeParameters, array(
                                            $this->parameterNames['currentPage'] => $pages->current + 1
                                        )
                                    )
                                ),
                                true
                            );?>
                        " onclick="<?php echo sprintf($paginatorOnclick, $pages->current + 1);?>">
                            &raquo;
                        </a>
                    </li>
                    
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">&raquo;</a>
                    </li>
                <?php endif;?>
                
            </ul>
            <?php endif; ?>
        </div>
    </div>
    <div class="span4 col-md-4 text-right">
        <?php echo $this->translate('Showing').' '.$this->paginator->getCurrentItemCount().' '.$this->translate('of').' '.$this->paginator->getTotalItemCount().' '.$this->translate('items'); ?>
    </div>
</div><!-- End Pagination -->
</form>
