<?php 
use ZfcDatagrid\Column;
use ZfcDatagrid\Column\Type;
use ZfcDatagrid\Column\Style;
?>

<form name="form_<?= $this->gridId; ?>" method="post" action="<?= $this->url(null, array(), array(), true); ?>">
    <input type="submit" class="hidden" name="hiddenSubmit" />
    <input type="hidden" name="<?= $this->parameterNames['sortColumn']; ?>" value="<?= $this->activeParameters[$this->parameterNames['sortColumn']]; ?>" />
    <input type="hidden" name="<?= $this->parameterNames['sortDirection']; ?>" value="<?= $this->activeParameters[$this->parameterNames['sortDirection']]; ?>" />
    
<div class="row-fluid">
    <div class="span3">
        <a href="#" class="btn btn-primary">Add new entry</a> 
    </div>
    
    <div class="span6 text-center">
        <?php if(isset($this->title)):?>
            <h3><?= $this->escapeHtml($this->title); ?></h3>
        <?php endif;?>
    </div>
    
    <div class="span3 text-right">
        <a class="hidden" href="<?= $this->url(null, 
                array(),
                array(
                    'query' => array(
                        $this->parameterNames['rendererType'] => 'tcpdf'
                    )
                ),
                true
            );?>" 
            class="btn
        ">
            Download PDF
        </a>
        <a class="hidden" href="<?= $this->url(null, 
                array(),
                array(
                    'query' => array(
                        $this->parameterNames['rendererType'] => 'excel'
                    )
                ),
                true
            );?>" 
            class="btn
        ">
            Download Excel
        </a>
        <a href="<?= $this->url(null, 
                array(),
                array(
                    'query' => array(
                        $this->parameterNames['rendererType'] => 'printPlain'
                    )
                ),
                true
            );?>" 
            class="btn
        ">
            Print plain
        </a>
    </div>
</div><!-- End title + actions -->

<?php 

$orderOnclick = 'document.forms[\'form_'.$this->gridId.'\'].elements[\'' . $this->parameterNames['sortColumn'] . '\'].value = \'%s\';';
$orderOnclick .= 'document.forms[\'form_'.$this->gridId.'\'].elements[\'' . $this->parameterNames['sortDirection'] . '\'].value = \'%s\';';
$orderOnclick.= 'document.forms[\'form_'.$this->gridId.'\'].submit(); return false;';

$classes = array('table', 'table-striped', 'table-bordered');
if($this->rowClickLink != '#'){
    $classes[] = 'table-hover';
}
?>
<input type="hidden" name="<?= $this->parameterNames['sortColumn']?>" />
<input type="hidden" name="<?= $this->parameterNames['sortDirection']?>" />

<table class="<?= implode(' ', $classes); ?>">
    <thead>
        <tr>
            <?php 
            foreach($this->columns as $column){
                /* @var $column \ZfcDatagrid\Column\AbstractColumn */
                $classes = array();
                $styles = array();
                
                $id = $column->getUniqueId();
                
                $label = $this->translate($column->getLabel());
                $width = $column->getWidth();
                if($width != ''){
                    $styles[] = 'width: '.$this->escapehtmlattr($width).'%';
                }
                
                
                if($column->isHidden() === true){
                    $classes[] = 'hidden';
                }
                if($column->getType() instanceof Type\Number){
                    $styles[] = 'text-align: right';
                }
                ?>
                <th id="<?= $this->escapehtmlattr($id); ?>" class="<?= implode(',', $classes); ?>" style="<?= implode(';', $styles); ?>">
                    
                    <?php if($column->isUserSortEnabled() === true): 
                        if($column->isSortActive() === true && $column->getSortActiveDirection() === 'ASC'){
                            $direction = 'DESC';
                        } else{
                            $direction = 'ASC';
                        }
                        ?>
                        <a href="<?= 
                            $this->url(null, 
                                array(),
                                array(
                                    'query' => array_merge($this->activeParameters, array(
                                            $this->parameterNames['sortColumn'] => $column->getUniqueId(),
                                            $this->parameterNames['sortDirection'] => $direction,
                                        )
                                    )
                                ),
                                true
                            );?>
                        " onclick="<?= sprintf($orderOnclick, $column->getUniqueId(), $direction); ?>">
                            <?= $this->escapeHtml($label); ?>
                        </a>
                    <?php else: ?>
                        <?= $this->escapeHtml($label); ?>
                    <?php endif; ?>
                    
                    <?php 
                    if($column->isSortActive() === true){
                        if($column->getSortActiveDirection() === 'ASC'):?>
                            <i class="icon-chevron-down"></i>
                        <?php else: ?>
                            <i class="icon-chevron-up"></i>
                        <?php endif;
                    }
                    ?>
                </th>
                <?php
            }
            ?>
        </tr>
        
        <!-- User filters -->
        <?php if($this->isUserFilterEnabled === true):?>
            <tr>
                <?php
                foreach($this->columns as $column){
                    /* @var $column \ZfcDatagrid\Column\AbstractColumn */

                    $classes = array();
                    if($column->isHidden() === true){
                        $classes[] = 'hidden';
                    }
                    
                    $htmlFilter = '';
                    if($column->isUserFilterEnabled() === true){
                        $htmlFilter = '<input type="text" name="toolbarFilters['.$column->getUniqueId().']" style="width: 80%" value="'.$column->getFilterActiveValue().'" />';
                    }
                    ?>
                    <td class="<?= implode(',', $classes); ?>">
                        <?= $htmlFilter; ?>
                    </td>
                    <?php
                }
                ?>
            </tr>
        <?php endif; ?>
    </thead><!-- END table header -->
    
    <!-- Start table BODY -->
    <tbody>
        <?php foreach($this->data as $row): ?>
            <?php if(isset($row['idConcated'])):?>
                <tr id="<?= $this->escapehtmlattr($row['idConcated']); ?>">
            <?php else:?>
                <tr>
            <?php endif; ?>
            
                <?php 
                foreach($this->columns as $column){
                    /* @var $column \ZfcDatagrid\Column\AbstractColumn */

                    $styles = array();
                    $classes = array();
                    
                    if($column->isHidden() === true){
                        $classes[] = 'hidden';
                    }
                    
                    $type = $column->getType();
                    if($type instanceof Type\Number){
                        $styles[] = 'text-align: right';
                    }
                    
                    if($column->hasStyles() === true){
                        foreach($column->getStyles() as $style){
                            /* @var $style \ZfcDatagrid\Column\Style\AbstractStyle */
                            if($style->isApply($row) === true){
                                if ($style instanceof Style\Bold) {
                                    $styles[] = 'font-weight: bold';
                                } elseif($style instanceof Style\Color\Red){
                                    $styles[] = 'color: red';
                                } else{
                                    throw new \Exception('Not defined yet: "'.get_class($style).'"');
                                }
                            }
                        }
                    }
                    
                    if($column instanceof Column\Image){
                        $value = ' <a href="#" class="thumbnail"><img src="'.$this->escapeHtmlAttr($row[$column->getUniqueId()]).'" /></a>';
                    } elseif($column instanceof Column\Action){
                        $actions = array();
                        foreach($column->getActions() as $action){
                            $icon = '';
                            if($action->hasIconClass() === true){
                                $icon = '<i class="'.$action->getIconClass().'"></i>';
                            }
                            $actions[] = '<a class="btn" href="'.$action->getLink().'">' . $icon . ' ' . $action->getLabel() . '</a>';
                        }
                        
                        $value = implode(' ', $actions);
                    } else{
                        $value = $this->escapeHtml($row[$column->getUniqueId()]);
                    }
                    
                    if($column instanceof Column\Standard && $this->rowClickLink != '#'){
                        $value = '<a href="'.$this->rowClickLink.'">'.$value.'</a>';
                    }
                    ?>
                    <td class="<?= implode(',', $classes); ?>" style="<?= implode(';', $styles); ?>">
                        <?= $value ?>
                    </td>
                    
                <?php
                }
                ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php
$pages = $this->paginator->getPages();

$paginatorOnclick = 'document.forms[\'form_'.$this->gridId.'\'].elements[\'' . $this->parameterNames['currentPage'] . '\'].value = %s;';
$paginatorOnclick.= 'document.forms[\'form_'.$this->gridId.'\'].submit(); return false;';
?>
<!-- Start Pagination -->
<div class="row-fluid">
    <div class="span4">
        <?= $this->translate('Page').' '.$this->paginator->getCurrentPageNumber().' '.$this->translate('of').' '.$this->paginator->count(); ?>
    </div>
    <div class="span4">
        <div class="pagination">
        
            <input type="hidden" name="<?= $this->parameterNames['currentPage']; ?>" value="<?= $pages->current; ?>" />
            
            <ul>
                <?php if($pages->current > 1):?>
                    <li><a href="<?= 
                            $this->url(null, 
                                array(),
                                array(
                                    'query' => array_merge($this->activeParameters, array(
                                            $this->parameterNames['currentPage'] => $pages->current - 1
                                        )
                                    )
                                ),
                                true
                            );?>
                        "  onclick="<?= sprintf($paginatorOnclick, $pages->current - 1);?>">
                            &laquo;
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">&laquo;</a>
                    </li>
                <?php endif;?>
                
                <?php foreach($pages->pagesInRange as $page):?>
                    <?php 
                    $add = '';
                    if($pages->current === $page){
                        $add = 'class="active"';
                    }
                    
                    if($pages->current != $page){
                        $url = $this->url($this->matchedRouteName, 
                            array(),
                            array(
                                'query' => array_merge($this->activeParameters, array(
                                        $this->parameterNames['currentPage'] => $page
                                    )
                                )
                            ),
                            true
                        );
                    } else{
                        $url = '#';
                    }
                    ?>
                    <li <?= $add; ?>>
                        <a href="<?= $url; ?>" onclick="<?= sprintf($paginatorOnclick, $page);?>">
                            <?= $page; ?>
                        </a>
                    </li>
                <?php endforeach; ?>
                
                <?php if($pages->current < $pages->pageCount): ?>
                    <li>
                        <a href="<?= 
                            $this->url($this->matchedRouteName, 
                                array(),
                                array(
                                    'query' => array_merge($this->activeParameters, array(
                                            $this->parameterNames['currentPage'] => $pages->current + 1
                                        )
                                    )
                                ),
                                true
                            );?>
                        " onclick="<?= sprintf($paginatorOnclick, $pages->current + 1);?>">
                            &raquo;
                        </a>
                    </li>
                    
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">&raquo;</a>
                    </li>
                <?php endif;?>
                
            </ul>
        </div>
    </div>
    <div class="span4 text-right">
        <?= $this->translate('Showing').' '.$this->paginator->getCurrentItemCount().' '.$this->translate('of').' '.$this->paginator->getTotalItemCount().' '.$this->translate('items'); ?>
    </div>
</div><!-- End Pagination -->
</form>
