<?php 
$parameterNames = $this->rendererOptions['parameterNames'];
?>
<div class="row-fluid" style="margin-bottom: 5px;">
    TOOLBAR
</div>

<table id="<?= $this->gridId; ?>"></table>
<div id="<?= $this->gridId; ?>_pager"></div>
                
<script>
var grid_<?= $this->gridId; ?> = $('#<?= $this->gridId; ?>').jqGrid({
	url: '<?= $this->url(null, array(), array(), true); ?>',

	caption: '<?= $this->title; ?>',

	autowidth : true,
    forceFit : false,
    shrinkToFit : true,
    gridview : true,
    hoverrows : true,
    viewrecords : true,
    
	mtype : 'POST',

	sortname: '<?= $this->activeParameters[$parameterNames['sortColumns']]; ?>',
	sortorder: '<?= $this->activeParameters[$parameterNames['sortDirections']]; ?>',
	
	prmNames : {
		page: '<?= $parameterNames['currentPage']; ?>',
		rows: '<?= $parameterNames['itemsPerPage']; ?>',
		sort: '<?= $parameterNames['sortColumns']; ?>',
		order: '<?= $parameterNames['sortDirections']; ?>',
		search: '<?= $parameterNames['isSearch']; ?>',
	},
	
	pager : '#<?= $this->gridId; ?>_pager',

    colModel: <?= $this->jqgridColumns($this->columns); ?>,

    datatype : 'local',
    jsonReader : {
        repeatitems : false,
        id : 'idConcated'
    },
});

grid_<?= $this->gridId; ?>.jqGrid('filterToolbar');

grid_<?= $this->gridId; ?>.jqGrid('setGridParam', {
    datatype : 'json'
}).trigger('reload');
grid_<?= $this->gridId; ?>.jqGrid()[0].addJSONData(<?= json_encode($this->data); ?>);
grid_<?= $this->gridId; ?>.trigger('reload');

//This is needed to load the data with ajax!
grid_<?= $this->gridId; ?>.jqGrid('setGridParam', {
    jsonReader : {
        repeatitems : false,
        id : 'idConcated',

        page : function(data) {
            if (data.data) {
                return data.data.<?= $parameterNames['currentPage']; ?>;
            }
        },

        records : function(data) {
            if (data.data) {
                return data.data.records;
            }
        },

        total : function(data) {
            if (data.data) {
                return data.data.total;
            }
        },

        root : function(data) {
            if (data.data) {
                return data.data.rows;
            }
        }
    }
});
</script>
