<div class="row-fluid" style="margin-bottom: 5px;">

    <!-- Actions (add, ...) -->
    <div class="span2">
        Here your can add global actions like "Add".<br />
        Change the toolbar with $grid-&gt;setToolbarTemplate('my-path/awesome-list/grid-toolbar');
    </div>
    
    <!-- Anything else (filter, ...) -->
    <div class="span6">
        E.g. you could add here custom filters from a select element
    </div>
    
    <!-- Export buttons -->
    <div class="span4 text-right">
        <?php echo $this->partial('zfc-datagrid/toolbar/export');?>
    </div>
    
</div>
